DROP TABLE IF EXISTS app_user CASCADE;
DROP INDEX IF EXISTS app_user_email_idx;
DROP TABLE IF EXISTS app_order CASCADE;


CREATE TABLE IF NOT EXISTS app_user
(id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 name  VARCHAR(150)                            NOT NULL,
 email VARCHAR(255) UNIQUE                     NOT NULL,
 CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE UNIQUE INDEX app_user_email_idx ON app_user USING btree (email);


CREATE TABLE IF NOT EXISTS app_order
(id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 name        VARCHAR(150)                            NOT NULL,
 description VARCHAR(1000)                           NOT NULL,
 status      VARCHAR(255)                            NOT NULL,
 user_id     BIGINT                                  NOT NULL,
 CONSTRAINT pk_app_order PRIMARY KEY (id),
 CONSTRAINT fk_order_to_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE RESTRICT
);